version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 7001:7001
    restart: on-failure
    volumes:
      - ./:/app
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= ${DB_PASS}
      - MYSQL_USER= ${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASS}
      - SERVICE_NAME=${DB_DRIVER}

    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:


