
#DROP DATABASE IF EXISTS bigouncefarms;

SET FOREIGN_KEY_CHECKS = 0 ;

DROP TABLE IF EXISTS address CASCADE ;
DROP TABLE IF EXISTS categories CASCADE ;
DROP TABLE IF EXISTS products CASCADE ;
DROP TABLE IF EXISTS reviews CASCADE ;
DROP TABLE IF EXISTS orders CASCADE ;
DROP TABLE IF EXISTS customers CASCADE ;
DROP TABLE IF EXISTS orderDetails CASCADE ;
DROP TABLE IF EXISTS categories CASCADE ;
DROP TABLE IF EXISTS payment CASCADE ;
