// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Address struct {
	ID            int64          `json:"id"`
	AddressUserID string         `json:"addressUserID"`
	OrderID       sql.NullString `json:"orderID"`
	Email         string         `json:"email"`
	Street        string         `json:"street"`
	AddressLine1  string         `json:"addressLine1"`
	AddressLine2  string         `json:"addressLine2"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	ZipCode       string         `json:"zipCode"`
}

type Category struct {
	ID           int64  `json:"id"`
	CategoryID   string `json:"categoryID"`
	CategoryName string `json:"categoryName"`
}

type Order struct {
	ID          int64         `json:"id"`
	OrderID     string        `json:"orderID"`
	Quantity    sql.NullInt32 `json:"quantity"`
	TotalAmount sql.NullInt64 `json:"totalAmount"`
	// When order created
	CreatedAt sql.NullString `json:"createdAt"`
}

type Product struct {
	ID                 int64        `json:"id"`
	ProductID          string       `json:"productID"`
	ImageUrlPublicID   string       `json:"imageUrlPublicID"`
	ImageUrlSecureID   string       `json:"imageUrlSecureID"`
	ProductName        string       `json:"productName"`
	ProductDescription string       `json:"productDescription"`
	Price              int64        `json:"price"`
	CreatedAt          sql.NullTime `json:"createdAt"`
}

type Review struct {
	ID           int64          `json:"id"`
	ReviewID     string         `json:"reviewID"`
	UserReviewID sql.NullString `json:"userReviewID"`
	Review       string         `json:"review"`
	CreatedAt    sql.NullTime   `json:"createdAt"`
}

type User struct {
	ID        int64        `json:"id"`
	UserID    string       `json:"userID"`
	FirstName string       `json:"firstName"`
	LastName  string       `json:"lastName"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"createdAt"`
}
